[project]
name = "kgraph"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
readme = "README.md"
dependencies = [

    "networkx>=3.6.1",
    "openpyxl>=3.1.5",
    "pandas>=3.0.1",
    "pydeps>=3.0.2",
    "pyshacl>=0.31.0",
    "rdflib>=7.6.0",
    "sqlitedict>=2.1.0",
]

[dependency-groups]
dev = [
    "gravis",
    "jupyter",
    "notebook",
    "matplotlib",
    "sphinx",
    "pylint",
    "black",
    "pytest-cov",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[tool.uv.sources]
gravis = { path = "../../../../../home/tomk/Documents/Coding/gravis/dist/gravis-0.1.1-py3-none-any.whl" }
