"""A utility for creating data-load pipelines to convert 
schema-bound (tabular) data to mastered, quality-checked
and approved rdf graph data"""

import os
from rdflib import Graph
import pandas as pd

# local imports
from schemamapping import SchemaMapping
from namemaster import NameMaster

class KGraphPipeline:
    def __init__(
            self,
            schema_def_location : str, 
            ontology_list : list[str], 
            mapping_config_location : str, 
            validation_shacl_list : list[str], 
            name_master_location : str
    ):
        """Setup parameters and configuration for Pipeline process
            schema_def - a filename describing the contents of a schema and expected data-types
            ontology_list - a list of ontology filenames used to define the target definitions of a schema mapping
            mapping_config - a filename locating a json schema-mapping document, 
                             joining schema_def values to elements defined in a target ontology
            validation_shacl_list - a list of shape-filenames used to validate content generated by the pipeline process
            namemaster_location - a filename location used to serve as a persistent record of key-value pairs
            """
        
        args = {"schema_def_location" : schema_def_location, 
                "ontology_list" : ontology_list, 
                "mapping_config_location" : mapping_config_location, 
                "validation_shacl_list" : validation_shacl_list, 
                "name_master_location" : name_master_location}
        for k,v in args.items():
            if isinstance(args, list):
                for a in v:
                    if not self._validate_file_exists(a):
                        raise FileExistsError(a)
            else:
                if not self._validate_file_exists(v):
                    raise FileExistsError(v)
            
        self.MappingObject = SchemaMapping(mapping_config_location)
        self.o_list = ontology_list


    def process(self, data : pd.DataFrame)->Graph:
        """Accept some data input as a dataframe and convert it
        into an rdflib graph using the parameterised process"""
        return Graph()
    
    @staticmethod
    def _validate_file_exists(filename : str) -> bool:
        filepath = os.path.abspath(filename)
        if os.path.isfile(filepath):
            return True
        else:
            # Generate logging/output signal and return fail
            return False


