"""A utility for creating data-load pipelines to convert
schema-bound (tabular) data to mastered, quality-checked
and approved rdf graph data"""

import os
from typing import Optional
import pandas as pd
from rdflib import Graph
from pyshacl import validate


# local imports
from kgraph.schemamapping import SchemaMapping
from kgraph.namemaster import NameMaster


class KGraphPipeline:
    def __init__(
        self,
        mapping_config_location: str,
        ontology_list: Optional[list[str]] = None,
        validation_shacl_list: Optional[list[str]] = None,
        name_master_location: Optional[str] = None,
    ):
        """Setup parameters and configuration for Pipeline process
        mapping_config - a filename locating a json schema-mapping document,
                         joining schema_def values to elements defined in a target ontology
        ontology_list - a list of ontology filenames used to define the target definitions of a schema mapping
        validation_shacl_list - a list of shape-filenames used to validate content generated by the pipeline process
        namemaster_location - a filename location used to serve as a persistent record of key-value pairs
        """

        args = {k: v for k, v in vars().items() if k != "self"}

        for k, v in args.items():
            if isinstance(v, list):
                for a in v:
                    if not self._validate_file_exists(a):
                        raise FileExistsError(
                            f"Problem with parameter `{k}` "
                            + f"there is no file at :`{a}`"
                        )
            else:
                if v is not None and not self._validate_file_exists(v):
                    raise FileExistsError(
                        f"Problem with parameter `{k}` there is no file at :`{v}`"
                    )

        self.mapping_object = SchemaMapping(mapping_config_location)
        self.expected_columns = set(self.mapping_object.referenced_columns) - set(
            self.mapping_object.glob_vars.keys()
        )
        self.o_list = ontology_list # TODO: expand the ontology awareness of the pipeline
        self.shacl_validations = validation_shacl_list
        self.shacl_validation_results = []

        if name_master_location is None:
            name_master_location = ":memory:"
        self.namemaster = NameMaster(name_master_location)

    def process(self, 
                data: pd.DataFrame,
                ignore_validate : bool = False) -> Graph:
        """Accept some data input as a dataframe and convert it
        into an rdflib graph using the parameterised process"""

        # Validate Columns from input data match expected mapping columns
        _, _, f_score = KGraphPipeline._lir_stats(
            set(data.columns), self.expected_columns
        )
        if not ignore_validate:
            if f_score < 0.95:
                # There's likely a problem with the file, in that there's not a high
                # correlation between the columns present and those expected by the
                # serialisation config
                raise ValueError(
                    f"Not a close enough match between expected columns {self.expected_columns} "
                    + f"and the columns presented in the data {data.columns}. Recheck and "
                    + "try again"
                )

        raw_g = self.mapping_object.to_rdf_graph(data)

        if self.shacl_validations is not None:
            for sh_v_filename in self.shacl_validations:
                s_g = Graph()
                s_g.parse(sh_v_filename)
                conforms, results_g, results_t = validate(
                    raw_g,
                    shacl_graph=s_g,
                    ont_graph=None,
                    inference="rdfs",
                    abort_on_first=False,
                    allow_infos=False,
                    allow_warnings=False,
                    meta_shacl=False,
                    advanced=False,
                    js=False,
                    debug=False,
                )
                self.shacl_validation_results.append((conforms, results_g, results_t))

        if any((c is False for c, g, t in self.shacl_validation_results)):
            print("SHACL validation fail! - see shacl_validation_results for details")

        master_graph = self.namemaster.master_graph(raw_g)
        return master_graph

    @staticmethod
    def _validate_file_exists(filename: str) -> bool:
        filepath = os.path.abspath(filename)
        if os.path.isfile(filepath):
            return True

        # Generate logging/output signal and return fail
        return False

    @staticmethod
    def _sets_to_lir(set_a, set_b):
        l, i, r = set_a - set_b, set_a.intersection(set_b), set_b - set_a
        return l, i, r

    @staticmethod
    def _lir_stats(set_a, set_b):
        l, i, r = KGraphPipeline._sets_to_lir(set_a, set_b)
        total_size, len_a, len_b = (
            sum((1 for v in [l, i, r] for e in v)),
            len(set_a),
            len(set_b),
        )
        precision = (len(i)) / (len(i) + len(l))
        recall = (len(i)) / (len(i) + len(r))
        if (precision + recall) != 0:
            f1_score = 2 * (precision * recall) / (precision + recall)
        else:
            f1_score = 0
        return precision, recall, f1_score
